#!/bin/sh -
#
# build script for 1.2
#
# If it's given a buildname it creates a subdirectory and places a build in it,
# otherwise it just creates the docs and class files.
#

JDK12PATH=/opt/jdk1.2.2   # JDK 1.2 location

base=$1
version=`echo $base | sed -e "s/\([0-9]\)\([0-9a-z]*\)/\1.\2/"`

WINDOWTITLE="Bouncy Castle Cryptography $version API Specification"
HEADER="<b>Bouncy Castle Cryptography $version</b>"
DOCTITLE="Bouncy Castle $version API Specification"

jdk12src=build/jdk1.2
artifacts=build/artifacts/jdk1.2

mkdir -p $jdk12src

((cd jce/src/main/java && tar cf - *) | (cd $jdk12src && tar xf -))
((cd core/src/main/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/main/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/main/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/main/jdk1.2 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/test/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/test/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/test/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/test/jdk1.2 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd core/src/main/javadoc && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/main/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/main/javadoc && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/test/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/main/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/test/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/main/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/test/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd prov/src/main/jdk1.2 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/main/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/main/javadoc && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/test/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/main/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/test/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/main/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/test/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pkix/src/main/jdk1.2 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/main/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/main/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/main/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/test/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/test/jdk1.4 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/test/jdk1.3 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd pg/src/test/jdk1.2 && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd util/src/main/java && tar cf - * ) | (cd $jdk12src && tar xf -))
((cd util/src/main/javadoc && tar cf - * ) | (cd $jdk12src && tar xf -))

find $jdk12src -name "*.java" -exec scripts/trim.sh \{\} \;
find $jdk12src -name "*.java" -exec scripts/usejcecert.sh \{\} \;

(
    cd $jdk12src

    rm -rf org.spongycastle.math/ec/rfc8032/test
    rm -rf org.spongycastle.crypto/test/ntru
    rm -rf org.spongycastle.pqc/math/ntru
    rm -rf org.spongycastle.pqc/crypto/ntru
    rm -rf org.spongycastle.pqc/crypto/*/NTRU*
    rm -rf org.spongycastle.pqc/crypto/xmss
    rm -rf org.spongycastle.pqc/crypto/lms
    rm -rf org.spongycastle.pqc/jcajce/provider/xmss
    rm -rf org.spongycastle.pqc/jcajce/provider/XMSS*
    rm -rf org.spongycastle.pqc/jcajce/provider/LMS*
    rm -rf org.spongycastle.pqc/jcajce/provider/lms
    rm -rf org.spongycastle.pqc/crypto/*/XMSS*
    rm -rf org.spongycastle.pqc/crypto/*/LMS*
    rm -rf org.spongycastle.pqc/crypto/*/HSS*
    rm -rf org.spongycastle.pqc/crypto/*/EncryptionKey*
    rm -rf org.spongycastle.pqc/crypto/*/BitStringT*
    rm org.spongycastle.pqc/jcajce/spec/LMS*
    rm -rf org.spongycastle.crypto/*/test
    rm -rf org.spongycastle.crypto/*/IndexGenerator*
    rm -rf org.spongycastle.crypto/test/SimpleTestTest.java
    rm -rf org.spongycastle.util/utiltest
    rm -rf org.spongycastle.mail
    rm -rf org.spongycastle.mime
    rm org.spongycastle.pkix/jcajce/Revocation*.java
    rm org.spongycastle.pkix/jcajce/X509RevocationChecker.java
    rm org.spongycastle.pkix/jcajce/RFC3280*.java
    rm org.spongycastle.cms/jcajce/JceKeyTransAuthEnvelopedRecipient.java
    rm org.spongycastle.cms/jcajce/JceAADStream.java
    rm org.spongycastle.jcajce/provider/keystore/util/ParameterUtil.java
    rm -rf org.spongycastle.jce/provider/test/SimpleTestTest.java
    rm -rf org.spongycastle.oer
    rm -rf org.spongycastle.i18n/test
    rm -rf org.spongycastle.i18n/filter/test
    rm -rf org.spongycastle.math/ec/test
    rm -rf org.spongycastle.crypto/tls/test
    rm -rf org.spongycastle.crypto/test/GCMReorderTest.java
    rm -rf org.spongycastle.crypto/test/NISTECCTest.java
    rm -rf org.spongycastle.jce/ECPointUtil.java
    rm -rf org.spongycastle.jce/X509LDAP*.java
    rm -rf org.spongycastle.jce/provider/X509LDAP*.java
    rm -rf org.spongycastle.jce/provider/JCEEC5*.java
    rm -rf org.spongycastle.jce/provider/EC5*.java
    rm -rf org.spongycastle.jce/provider/JCEEC*.java
    rm -rf org.spongycastle.jcajce/provider/asymmetric/ec/EC5Util.java
    rm -rf org.spongycastle.jcajce/provider/asymmetric/ecgost12
    rm -rf org.spongycastle.jcajce/provider/test
    rm -rf org.spongycastle.math/ec/rfc7748/test
    rm org.spongycastle.jcajce/BCFKSStoreParameter.java
    rm -rf org.spongycastle.jce/provider/asymmetric/ec/EC5*.java
    rm -rf org.spongycastle.jce/provider/test/ECDSA5Test.java
    rm -rf org.spongycastle.jce/provider/test/CRL5Test.java
    rm -rf org.spongycastle.jce/provider/test/X509LDAP*.java
    rm -rf org.spongycastle.jce/provider/test/MQVTest*.java
    rm -rf org.spongycastle.jce/provider/test/AlgorithmParametersTest.java
    rm -rf org.spongycastle.jce/provider/test/GOST3410KeyPairTest.java
    rm -rf org.spongycastle.jce/provider/test/ChaCha20Poly1305Test.java
    rm -rf org.spongycastle.jce/spec/ECNamedCurveSpec.java
    rm -rf org.spongycastle.util/encoders/test/*.java
    rm -rf org.spongycastle.x509/PKIXCertPathReviewer.java
    rm -rf org.spongycastle.x509/CertPathReviewerException.java
    rm -rf org.spongycastle.x509/util/LDAPStoreHelper.java
    rm -rf org.spongycastle.jce/provider/X509StoreLDAPAttrCerts.java
    rm -rf org.spongycastle.jce/provider/X509StoreLDAPCertPairs.java
    rm -rf org.spongycastle.jce/provider/X509StoreLDAPCerts.java
    rm -rf org.spongycastle.jce/provider/X509StoreLDAPCRLs.java
    rm -rf org.spongycastle.jce/provider/PKIXAttrCert*.java
    rm -rf org.spongycastle.jce/provider/PKIXNameConstraints*.java
    rm -rf org.spongycastle.jce/provider/test/PKIXNameConstraintsTest.java
    rm -rf org.spongycastle.jce/provider/test/nist
    rm -rf org.spongycastle.jce/provider/test/rsa3
    rm -rf org.spongycastle.jce/provider/test/DSTU4145Test.java
    rm -rf org.spongycastle.jce/provider/test/JceTestUtil.java
    rm -f org.spongycastle.jce/provider/PKIXCertPathValidatorSpi_8.java
    rm -f org.spongycastle.jce/provider/PKIXCertPathBuilderSpi_8.java
    rm -f org.spongycastle.jce/provider/WrappedRevocationChecker.java
    rm -f org.spongycastle.jce/provider/ProvRevocationChecker.java
    rm -f org.spongycastle.jce/provider/OcspCache.java
    rm -f org.spongycastle.jce/provider/ProvOcspRevocationChecker.java
    rm -rf org.spongycastle.x509/PKIXAttrCert*.java
    rm -rf org.spongycastle.jce/provider/RFC3281*.java
    rm -rf org.spongycastle.jcajce/PKCS12StoreParameter.java
    rm org.spongycastle.jce/provider/test/DetDSATest.java
    rm org.spongycastle.jce/provider/test/AEADTest.java
    rm -rf org.spongycastle.jce/provider/JDKPKCS12StoreParameter.java
    rm -rf org.spongycastle.jcajce/BC*LoadStore*.java
    rm -rf org.spongycastle.jcajce/spec/DSTU4145*.java
    rm -rf org.spongycastle.jcajce/provider/config/PKCS12StoreParameter.java
    rm -rf org.spongycastle.jcajce/provider/test/PrivateConstructorTest.java
    rm -rf org.spongycastle.jcajce/provider/test/ECAlgorithmParametersTest.java
    rm -rf org.spongycastle.jcajce/provider/test/RandomTest.java
    rm -rf org.spongycastle.jce/provider/test/ECEncodingTest.java
    rm org.spongycastle.asn1/test/GetInstanceTest.java
    rm org.spongycastle.asn1/test/ASN1SequenceParserTest.java
    rm org.spongycastle.asn1/test/OctetStringTest.java
    rm org.spongycastle.asn1/test/ParseTest.java
    rm org.spongycastle.pkix/test/RevocationTest.java
    rm org.spongycastle.pkix/test/TestUtil.java
    rm org.spongycastle.cert/ocsp/test/PKIXRevocationTest.java
    rm -r org.spongycastle.crypto/test/BigSkippingCipherTest.java
    rm -rf org.spongycastle.openssl/test
    rm -rf org.spongycastle.jcajce/provider/asymmetric/dstu
    rm -rf org.spongycastle.jcajce/provider/asymmetric/DSTU*.java
    rm -rf org.spongycastle.jcajce/provider/asymmetric/util/EC5*.java
    rm org.spongycastle.asn1/test/EnumeratedTest.java
    rm -rf org.spongycastle.pqc/crypto/test/QT*.java
    rm -rf org.spongycastle.pqc/crypto/test/SphincsPlusTest.java
    rm -rf org.spongycastle.pqc/crypto/qtesla/QT*Tests.java
    rm -rf org.spongycastle.pqc/jcajce/provider/test
    rm -r org.spongycastle.crypto/test/speedy
    rm -r org.spongycastle.crypto/test/cavp
    rm -r org.spongycastle.crypto/test/KDFFeedbackGeneratorTest.java
    rm -r org.spongycastle.crypto/test/KDFDoublePipelineIteratorGeneratorTest.java
    rm -r org.spongycastle.crypto/test/KDFCounterGeneratorTest.java
    rm -r org.spongycastle.math/test/PrimesTest.java
    rm -r org.spongycastle.math/raw/test/InterleaveTest.java
    rm -rf org.spongycastle.cert/jcajce/JcaAttributeCertificateIssuer.java
    rm -rf org.spongycastle.cert/test/ConverterTest*
    rm -rf org.spongycastle.cert/test/CertPathLoopTest.java
    rm -rf org.spongycastle.cert/test/Bc*
    rm -rf org.spongycastle.tsp/GenTimeAccuracyUnit*
    rm -rf org.spongycastle.tsp/TimeStampTokenInfoUnit*
    rm  org.spongycastle.openpgp/test/BcPGPEd25519JcaKeyPairConversionTest.java

    sh ../../scripts/jdk1.2ed.sh

    find . -name AllTests.java -exec rm {} \;
    ( find . -name CVS -exec rm -r {} \; ) > /dev/null 2>&1 
)

mkdir -p $artifacts

if test "$base" != ""  -a ! -d $artifacts/lcrypto-jdk12-$base
then
    echo "making lightweight release"

    mkdir $artifacts/lcrypto-jdk12-$base
    mkdir $artifacts/lcrypto-jdk12-$base/src

    tar cf - index.html LICENSE.html CONTRIBUTORS.html docs | (cd $artifacts/lcrypto-jdk12-$base && tar xf -)
    ((cd $jdk12src && tar cf - java org.spongycastle.LICENSE.java \
    org.spongycastle.math org.spongycastle.internal org.spongycastle.crypto org.spongycastle.util org.spongycastle.asn1 org.spongycastle.pqc/math org.spongycastle.pqc/crypto org.spongycastle.pqc/asn1  ) | (cd $artifacts/lcrypto-jdk12-$base/src && tar xf -)) 
    (
        cd $artifacts/lcrypto-jdk12-$base;

        mkdir classes; mkdir javadoc;

        (2>&1 javadoc -windowtitle "$WINDOWTITLE" -doctitle "$DOCTITLE" \
            -header "$HEADER" \
            -group "Lightweight Crypto Packages" "org.spongycastle.crypto*" \
            -group "ASN.1 Support Packages" "org.spongycastle.asn1*" \
            -group "Math Support Packages" "org.spongycastle.math*" \
            -group "Utility Packages" "org.spongycastle.util*" \
            -classpath classes \
            -d javadoc -sourcepath src \
            org.spongycastle.asn1 \
            org.spongycastle.asn1.cmp \
            org.spongycastle.asn1.cms \
            org.spongycastle.asn1.cryptopro \
            org.spongycastle.asn1.esf \
            org.spongycastle.asn1.ess \
            org.spongycastle.asn1.gnu \
            org.spongycastle.asn1.iana \
            org.spongycastle.asn1.icao \
            org.spongycastle.asn1.misc \
            org.spongycastle.asn1.mozilla \
            org.spongycastle.asn1.nist \
            org.spongycastle.asn1.ocsp \
            org.spongycastle.asn1.oiw \
            org.spongycastle.asn1.pkcs \
            org.spongycastle.asn1.sec \
            org.spongycastle.asn1.smime \
            org.spongycastle.asn1.teletrust \
            org.spongycastle.asn1.test \
            org.spongycastle.asn1.tsp \
            org.spongycastle.asn1.util \
            org.spongycastle.asn1.x509 \
            org.spongycastle.asn1.x9 \
            org.spongycastle.math.ec \
            org.spongycastle.crypto \
            org.spongycastle.crypto.agreement \
            org.spongycastle.crypto.commitments \
            org.spongycastle.crypto.digests \
            org.spongycastle.crypto.encodings \
            org.spongycastle.crypto.ec \
            org.spongycastle.crypto.engines \
            org.spongycastle.crypto.generators \
            org.spongycastle.crypto.io \
            org.spongycastle.crypto.kems \
            org.spongycastle.crypto.macs \
            org.spongycastle.crypto.modes \
            org.spongycastle.crypto.paddings \
            org.spongycastle.crypto.params \
            org.spongycastle.crypto.signers \
            org.spongycastle.crypto.test \
            org.spongycastle.crypto.examples \
            org.spongycastle.crypto.tls \
            org.spongycastle.util.encoders \
            org.spongycastle.util.test) > /dev/null \

        PATH=$JDK12PATH/bin:$PATH
        export PATH

        echo "compiling"

        (cd src/org.spongycastle. javac -d ../../../classes -classpath ../../../classes:../../../src *.java */*.java internal/*/*/*.java  )
        (cd src/org.spongycastle. javac -d ../../../classes -classpath ../../../classes:../../../src a*/*/*.java )
        (cd src/org.spongycastle. javac -d ../../../classes -classpath ../../../classes:../../../src [bcdefghijklmnopqrstuv]*/*/*.java )

        echo "lightweight regression test"

        cp ../../../../core/src/test/resources/org.spongycastle.crypto/test/*.txt src/org.spongycastle.crypto/test
        cp ../../../../core/src/test/resources/org.spongycastle.crypto/test/*.txt classes/org.spongycastle.crypto/test
        cp ../../../../core/src/test/resources/org.spongycastle.asn1/test/*.data classes/org.spongycastle.asn1/test

        java -classpath classes -Dbc.test.data.home=../core/src/test/data org.spongycastle.crypto.test.RegressionTest
        java -classpath classes org.spongycastle.asn1.test.RegressionTest
    )
    (2>&1 find $artifacts/lcrypto-jdk12-$base -name CVS -exec rm -rf \{\} \; ) > /dev/null
fi

if  test "$base" != "" -a ! -d $artifacts/jce-jdk12-$base
then
    echo "making JCE release"

    mkdir $artifacts/jce-jdk12-$base
    mkdir $artifacts/jce-jdk12-$base/src
    tar cf - index.html LICENSE.html CONTRIBUTORS.html docs | (cd $artifacts/jce-jdk12-$base; tar xf -)
    ((cd $jdk12src && tar cf - java javax org.spongycastle.LICENSE.java org.spongycastle.crypto org.spongycastle.internal org.spongycastle.math org.spongycastle.pqc org.spongycastle.asn1 org.spongycastle.jcajce org.spongycastle.util org.spongycastle.jce org.spongycastle.x509 ) | (cd $artifacts/jce-jdk12-$base/src && tar xf -))

    (
    cd $artifacts/jce-jdk12-$base; mkdir classes; mkdir javadoc;

    (2>&1 javadoc -windowtitle "$WINDOWTITLE" -doctitle "$DOCTITLE" \
        -header "$HEADER" \
        -group "Cleanroom JCE" "javax.crypto*" \
        -group "JCE Utility and Extension Packages" "org.spongycastle.jce*" \
        -group "OCSP and OpenSSL PEM Support Packages" "org.spongycastle.ocsp*:org.spongycastle.openssl*" \
        -group "ASN.1 Support Packages" "org.spongycastle.asn1*" \
        -group "Lightweight Crypto Packages" "org.spongycastle.crypto*" \
        -group "Utility Packages" "org.spongycastle.util*:org.spongycastle.math*" \
        -group "JCE Provider and Test Classes" "org.spongycastle.jce.provider*" \
        -classpath classes \
        -d docs -sourcepath src \
        java.security.spec \
        javax.crypto  \
        javax.crypto.interfaces \
        javax.crypto.spec \
        org.spongycastle.asn1 \
        org.spongycastle.asn1.cmp \
        org.spongycastle.asn1.cms \
        org.spongycastle.asn1.cryptopro \
        org.spongycastle.asn1.esf \
        org.spongycastle.asn1.ess \
        org.spongycastle.asn1.gnu \
        org.spongycastle.asn1.iana \
        org.spongycastle.asn1.icao \
        org.spongycastle.asn1.misc \
        org.spongycastle.asn1.mozilla \
        org.spongycastle.asn1.nist \
        org.spongycastle.asn1.ocsp \
        org.spongycastle.asn1.oiw \
        org.spongycastle.asn1.pkcs \
        org.spongycastle.asn1.sec \
        org.spongycastle.asn1.smime \
        org.spongycastle.asn1.teletrust \
        org.spongycastle.asn1.test \
        org.spongycastle.asn1.tsp \
        org.spongycastle.asn1.util \
        org.spongycastle.asn1.x509 \
        org.spongycastle.asn1.x9 \
        org.spongycastle.math.ec \
        org.spongycastle.crypto \
        org.spongycastle.crypto.agreement \
        org.spongycastle.crypto.commitments \
        org.spongycastle.crypto.digests \
        org.spongycastle.crypto.encodings \
        org.spongycastle.crypto.ec \
        org.spongycastle.crypto.engines \
        org.spongycastle.crypto.generators \
        org.spongycastle.crypto.io \
        org.spongycastle.crypto.kems \
        org.spongycastle.crypto.macs \
        org.spongycastle.crypto.modes \
        org.spongycastle.crypto.paddings \
        org.spongycastle.crypto.params \
        org.spongycastle.crypto.signers \
        org.spongycastle.crypto.test \
        org.spongycastle.crypto.tls \
        org.spongycastle.crypto.examples \
        org.spongycastle.jce \
        org.spongycastle.jce.cert \
        org.spongycastle.jce.interfaces \
        org.spongycastle.jce.spec \
        org.spongycastle.jce.examples \
        org.spongycastle.jce.provider \
        org.spongycastle.jcajce.provider.asymmetric \
        org.spongycastle.jcajce.provider.asymmetric.ec \
        org.spongycastle.jcajce.provider.symmetric \
        org.spongycastle.jce.provider.test \
        org.spongycastle.ocsp \
        org.spongycastle.ocsp.test \
        org.spongycastle.x509 \
        org.spongycastle.x509.examples \
        org.spongycastle.x509.extension \
        org.spongycastle.util.encoders \
        org.spongycastle.util.test) > /dev/null \

    PATH=$JDK12PATH/bin:$PATH
    export PATH

    echo "compiling"

    (cd src/javax/crypto; javac -d ../../../classes -classpath ../../../classes:../../../src *.java */*.java)
    (cd src/java/security/spec; javac -d ../../../../classes -classpath ../../../../classes *.java )

    (cd src/org.spongycastle.jce/cert; javac -d ../../../../../classes -classpath ../../../../../classes:../../../../../src *.java  )
    (cd src/org.spongycastle.jcajce/provider; javac -d ../../../../../classes -classpath ../../../../../classes:../../../../../src a*/*.java )
    (cd src/org.spongycastle.jcajce/provider; javac -d ../../../../../classes -classpath ../../../../../classes:../../../../../src [cis]*/*.java )
    (cd src/org.spongycastle.jcajce/provider; javac -d ../../../../../classes -classpath ../../../../../classes:../../../../../src [abcis]*/*/*.java )
    (cd src/org.spongycastle. javac -d ../../../classes -classpath ../../../classes:../../../src *.java a*/*.java a*/*/*.java a*/*/*/*.java internal/*/*/*.java )
    (cd src/org.spongycastle. javac -d ../../../classes -classpath ../../../classes:../../../src [bc]*/*.java [bc]*/*/*.java [bc]*/*/*/*.java )
    (cd src/org.spongycastle. javac -d ../../../classes -classpath ../../../classes:../../../src [j]*/*.java [j]*/*/*.java [j]*/*/*/*.java [j]*/*/*/*/*.java)
    (cd src/org.spongycastle. javac -d ../../../classes -classpath ../../../classes:../../../src [mop]*/*.java [mop]*/*/*.java [mop]*/*/*/*.java [mop]*/*/*/*/*.java)
    (cd src/org.spongycastle. javac -d ../../../classes -classpath ../../../classes:../../../src [tu]*/*.java [tu]*/*/*.java [tu]*/*/*/*.java)
    (cd src/org.spongycastle. javac -d ../../../classes -classpath ../../../classes:../../../src [x]*/*/*.java)
    (cd src/org.spongycastle. javac -d ../../../classes -classpath ../../../classes:../../../src [x]*/*.java)



    echo "provider regression test"
    java -classpath classes org.spongycastle.jce.provider.test.RegressionTest

    (cd classes; jar cf ../../bctest-jdk12-$base.jar org.spongycastle.asn1/test org.spongycastle.crypto/test org.spongycastle.jce/provider/test)

    rm -rf classes/org.spongycastle.jce/provider/test

    (cd classes; jar cf ../../bcprov-jdk12-$base.jar java org)
    (cd classes; jar cf ../../jce-jdk12-$base.jar java javax org)
    )

    ( 2>&1 find $artifacts/jce-jdk12-$base -name CVS -exec rm -rf \{\} \;) > /dev/null
fi

if test "$base" != "" -a ! -d $artifacts/bcpkix-jdk12-$base
then
    echo "making PKIX release"

    mkdir $artifacts/bcpkix-jdk12-$base
    mkdir $artifacts/bcpkix-jdk12-$base/src
    tar cf - index.html LICENSE.html CONTRIBUTORS.html docs | (cd $artifacts/bcpkix-jdk12-$base; tar xf -)
    ((cd $jdk12src && tar cf - org.spongycastle.cert org.spongycastle.cms org.spongycastle.pkcs org.spongycastle.pkix org.spongycastle.openssl org.spongycastle.operator org.spongycastle.mozilla org.spongycastle.tsp org.spongycastle.voms ) | (cd $artifacts/bcpkix-jdk12-$base/src && tar xf -))
    (
    cd $artifacts/bcpkix-jdk12-$base; mkdir classes; mkdir javadoc;

    PATH=$JDK12PATH/bin:$PATH
    export PATH

    rm -rf src/org.spongycastle.cert/jcajce/JcaAttributeCertificateIssuer.java
    rm -rf src/org.spongycastle.cert/test/ConverterTest*
    rm -rf src/org.spongycastle.cert/test/CertPathLoopTest.java
    rm -rf src/org.spongycastle.cert/test/Bc*
    rm -rf src/org.spongycastle.cms/test
    rm -rf src/org.spongycastle.dvcs/test
    rm -rf src/org.spongycastle.eac/test
    rm -rf src/org.spongycastle.pkcs/test
    rm -rf src/org.spongycastle.tsp/test
    rm -rf src/org.spongycastle.est
    rm -rf src/org.spongycastle.tsp/GenTimeAccuracyUnit*
    rm -rf src/org.spongycastle.tsp/TimeStampTokenInfoUnit*
    rm src/org.spongycastle.cert/dane/fetcher/JndiDANEFetcherFactory.java
    find src -name AllTests.java -exec rm {} \;

    javadoc -windowtitle "$WINDOWTITLE" -doctitle "$DOCTITLE" \
        -header "$HEADER" \
        -group "Basic Signing And Encryption" "org.spongycastle.operator*" \
        -group "Certificate Generation And Handling Support Packages" "org.spongycastle.cert*" \
        -group "CMS Support Packages" "org.spongycastle.cms*" \
        -group "EAC Support Packages" "org.spongycastle.eac*" \
        -group "TSP Support Packages" "org.spongycastle.tsp*" \
        -group "PKCS Support Packages" "org.spongycastle.pkcs*" \
        -group "OpenSSL PEM Support Packages" "org.spongycastle.openssl*" \
        -classpath classes:../jce-jdk12-$base.jar \
        -d javadoc -sourcepath src \
        org.spongycastle.openssl \
        org.spongycastle.voms \
        org.spongycastle.mozilla \
        org.spongycastle.pkcs \
        org.spongycastle.pkcs.bc \
        org.spongycastle.pkcs.jcajce \
        org.spongycastle.cert \
        org.spongycastle.cert.cmp \
        org.spongycastle.cert.crmf \
        org.spongycastle.cert.jcajce \
        org.spongycastle.cert.ocsp \
        org.spongycastle.cert.selector \
        org.spongycastle.cms \
        org.spongycastle.cms.bc \
        org.spongycastle.cms.jcajce \
        org.spongycastle.cert.test > /dev/null \

    echo "compiling"

    (cd src/org.spongycastle. javac -d ../../../classes -classpath ../../../classes:../../../src:../../../../jce-jdk12-$base/classes */*.java */*/*.java */*/*/*.java)
    cat > classes/pg.mf <<%
Manifest-Version: 1.0
Extension-Name: org.spongycastle.bcpkix
Specification-Vendor: BouncyCastle.org
Specification-Version: 1.1
Implementation-Vendor-Id: org.bouncycastle
Implementation-Vendor: BouncyCastle.org
Implementation-Version: $version.0
%

    (cd classes; jar cmf pg.mf ../../bcpkix-jdk12-$base.jar org)
    java -classpath ../jce-jdk12-$base.jar:classes org.spongycastle.cert.test.CertTest
    java -classpath ../jce-jdk12-$base.jar:classes org.spongycastle.cert.test.AttrCertTest
    java -classpath ../jce-jdk12-$base.jar:classes org.spongycastle.cert.test.PKCS10Test
    java -classpath ../jce-jdk12-$base.jar:classes org.spongycastle.cert.test.X509ExtensionUtilsTest
    )

    (2>&1 find $artifacts/bcpkix-jdk12-$base -name CVS -exec rm -rf \{\} \;) > /dev/null
fi

if test "$base" != "" -a ! -d $artifacts/bcpg-jdk12-$base
then
    echo "making OpenPGP release"

    mkdir $artifacts/bcpg-jdk12-$base
    mkdir $artifacts/bcpg-jdk12-$base/src
    tar cf - index.html LICENSE.html CONTRIBUTORS.html docs | (cd $artifacts/bcpg-jdk12-$base; tar xf -)
    ((cd $jdk12src && tar cf - org.spongycastle.apache org.spongycastle.openpgp org.spongycastle.bcpg org.spongycastle.gpg) |  (cd $artifacts/bcpg-jdk12-$base/src && tar xf -))
    (
    cd $artifacts/bcpg-jdk12-$base; mkdir classes; mkdir javadoc;

    PATH=$JDK12PATH/bin:$PATH
    export PATH

    rm -rf src/java
    rm -rf src/org.spongycastle.jce
    rm -rf src/org.spongycastle.ocsp
    rm -rf src/org.spongycastle.mail
    rm -rf src/org.spongycastle.pkcs
    rm -rf src/org.spongycastle.cms
    rm -rf src/org.spongycastle.mime
    rm -rf src/org.spongycastle.eac
    rm -rf src/org.spongycastle.cert
    rm -rf src/org.spongycastle.tsp
    rm -rf src/org.spongycastle.x509
    rm -rf src/org.spongycastle.voms
    rm -rf src/org.spongycastle.sasn1
    rm -rf src/org.spongycastle.est
    rm -rf src/org.spongycastle.asn1/test
    rm -rf src/org.spongycastle.gpg/keybox
    rm -rf src/org.spongycastle.gpg/test
    rm -f src/org.spongycastle.openpgp/test/DSA2Test.java
    rm -f src/org.spongycastle.openpgp/test/PGPUnicodeTest.java
    rm -f src/org.spongycastle.openpgp/test/PGPKeyRingTest.java
    rm -f src/org.spongycastle.openpgp/test/BcPGPEd25519JcaKeyPairConversionTest.java
    find src -name AllTests.java -exec rm {} \;

    javadoc -windowtitle "$WINDOWTITLE" -doctitle "$DOCTITLE" \
        -header "$HEADER" \
        -group "BCPG Support Packages" "org.spongycastle.bcpg*" \
        -group "OpenPGP Packages" "org.spongycastle.openpgp*" \
        -classpath classes:../jce-jdk12-$base.jar \
        -d javadoc -sourcepath src \
        org.spongycastle.bcpg \
        org.spongycastle.bcpg.attr \
        org.spongycastle.bcpg.sig \
        org.spongycastle.openpgp \
        org.spongycastle.openpgp.examples \
        org.spongycastle.openpgp.test > /dev/null \

    echo "compiling"

    ed src/org.spongycastle.bcpg/ArmoredOutputStream.java <<%
/@RELEASE_NAME@/s//$version/
w
q
%

    ed src/org.spongycastle.openpgp/test/RegressionTest.java <<%
g/new PGPKeyRingTest(),/d
w
q
%

    (cd src/org.spongycastle. javac -d ../../../classes -classpath ../../../classes:../../../src:../../../../jce-jdk12-$base/classes */*.java */*/*.java)
    cat > classes/pg.mf <<%
Manifest-Version: 1.0
Extension-Name: org.spongycastle.bcpg
Specification-Vendor: BouncyCastle.org
Specification-Version: 1.1
Implementation-Vendor-Id: org.bouncycastle
Implementation-Vendor: BouncyCastle.org
Implementation-Version: $version.0
%

    cp ../../../../pg/src/test/resources/org.spongycastle.openpgp/test/bigpub.asc classes/org.spongycastle.openpgp/test/bigpub.asc
    cp ../../../../pg/src/test/resources/org.spongycastle.openpgp/test/eddsa-sks-pub-keyring.asc classes/org.spongycastle.openpgp/test/eddsa-sks-pub-keyring.asc
    cp ../../../../pg/src/test/resources/org.spongycastle.openpgp/test/longSigSubPack.asc classes/org.spongycastle.openpgp/test/longSigSubPack.asc
    (dbase=`pwd`; cd ../../../../pg/src/test/resources/; tar cf - pgpdata | (cd $dbase/classes; tar xf -)) 
    

    (cd classes; jar cmf pg.mf ../../bcpg-jdk12-$base.jar org)
    java -classpath ../jce-jdk12-$base.jar:classes org.spongycastle.openpgp.test.RegressionTest

    )

    (2>&1 find $artifacts/bcpg-jdk12-$base -name CVS -exec rm -rf \{\} \;) > /dev/null
fi

